[greeter]
background=#f2f1e5
user-background=false
hide-user-image=true
font-name=Iosevka Oui 11
xft-antialias=true
xft-dpi=144
xft-hintstyle=slight
indicators=~host;~spacer;~clock;~spacer;~session;~power
clock-format=%a %b %d  %H:%M
position=50% 50%
